# Generated by Django 4.2.16 on 2024-11-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=100)),
            ],
        ),
    ]
